### ISSUE TITLE
how to make it work

### ISSUE THREAD

**Issue by yuuuxt** [ninoseki/vscode-mogami#37]
I used pylens before and now switch to mogami, but I haven't made it working. In the stable vscode version I see hovering labels as before, and in the latest insider version seems nothing appears:

![image](https://github.com/ninoseki/vscode-mogami/assets/3153534/74dcbd94-9d09-4c1f-b542-78b013d4d23e)

(using 1.90.0-insider and latest mogami 0.0.20 on win 10 x64.)

**Comment by ninoseki** [comment]
It works in my laptop and so I cannot verify your claim.
Maybe I can do something if you could share error logs. (ref. https://stackoverflow.com/questions/44188262/where-are-the-vscode-error-logs-for-extensions)

**Comment by yuuuxt** [comment]
Sure: 

> 2024-05-27 00:36:11.312 [info] Extension host with pid 25784 started
2024-05-27 00:36:11.313 [info] Skipping acquiring lock for c:\software\VSCode-Insiders\data\user-data\User\workspaceStorage\9a526cc331b49ab2e543735687cd734b.
2024-05-27 00:36:11.317 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-05-27 00:36:11.337 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-05-27 00:36:11.340 [info] ExtensionService#_doActivateExtension ninoseki.vscode-mogami, startup: true, activationEvent: 'workspaceContains:pyproject.toml'
2024-05-27 00:36:11.442 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-05-27 00:36:11.468 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-05-27 00:36:11.608 [info] Eager extensions activated
2024-05-27 00:36:11.618 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-05-27 00:36:11.621 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-05-27 00:36:11.629 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender, startup: false, activationEvent: 'onStartupFinished'
2024-05-27 00:36:12.345 [error] [ninoseki.vscode-mogami] provider FAILED
2024-05-27 00:36:12.346 [error] Error: [getWordRangeAtPosition]: ignoring custom regexp '^(?<name>)(?<rest>.+)?$' because it matches the empty string.
	at d.y (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:1838)
	at Object.getWordRangeAtPosition (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:256)
	at vc.parseDocumentPosition (c:\software\VSCode-Insiders\data\extensions\ninoseki.vscode-mogami-0.0.20\dist\extension.js:34:753)
	at vc.provideHover (c:\software\VSCode-Insiders\data\extensions\ninoseki.vscode-mogami-0.0.20\dist\extension.js:32:3314)
	at I.provideHover (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:101281)
	at c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:132072
	at Ie.s (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:129479)
	at Ie.$provideHover (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:132059)
	at E.S (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5970)
	at E.Q (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5736)
	at E.M (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:4723)
	at E.L (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:3589)
	at n.value (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:2282)
	at l.y (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:664)
	at l.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:881)
	at s.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14502)
	at n.value (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:8481)
	at l.y (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:664)
	at l.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:881)
	at s.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14502)
	at MessagePortMain.<anonymous> (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:6631)
	at MessagePortMain.emit (node:events:514:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
2024-05-27 00:36:12.620 [error] [ninoseki.vscode-mogami] provider FAILED
2024-05-27 00:36:12.620 [error] Error: [getWordRangeAtPosition]: ignoring custom regexp '^(?<name>)(?<rest>.+)?$' because it matches the empty string.
	at d.y (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:1838)
	at Object.getWordRangeAtPosition (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:256)
	at vc.parseDocumentPosition (c:\software\VSCode-Insiders\data\extensions\ninoseki.vscode-mogami-0.0.20\dist\extension.js:34:753)
	at vc.provideHover (c:\software\VSCode-Insiders\data\extensions\ninoseki.vscode-mogami-0.0.20\dist\extension.js:32:3314)
	at I.provideHover (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:101281)
	at c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:132072
	at Ie.s (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:129479)
	at Ie.$provideHover (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:132059)
	at E.S (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5970)
	at E.Q (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5736)
	at E.M (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:4723)
	at E.L (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:3589)
	at n.value (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:2282)
	at l.y (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:664)
	at l.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:881)
	at s.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14502)
	at n.value (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:8481)
	at l.y (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:664)
	at l.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:881)
	at s.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14502)
	at MessagePortMain.<anonymous> (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:6631)
	at MessagePortMain.emit (node:events:514:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
2024-05-27 00:36:13.804 [error] [ninoseki.vscode-mogami] provider FAILED
2024-05-27 00:36:13.804 [error] Error: [getWordRangeAtPosition]: ignoring custom regexp '^(?<name>)(?<rest>.+)?$' because it matches the empty string.
	at d.y (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:1838)
	at Object.getWordRangeAtPosition (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:256)
	at vc.parseDocumentPosition (c:\software\VSCode-Insiders\data\extensions\ninoseki.vscode-mogami-0.0.20\dist\extension.js:34:753)
	at vc.provideHover (c:\software\VSCode-Insiders\data\extensions\ninoseki.vscode-mogami-0.0.20\dist\extension.js:32:3314)
	at I.provideHover (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:101281)
	at c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:132072
	at Ie.s (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:129479)
	at Ie.$provideHover (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:132059)
	at E.S (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5970)
	at E.Q (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5736)
	at E.M (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:4723)
	at E.L (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:3589)
	at n.value (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:2282)
	at l.y (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:664)
	at l.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:881)
	at s.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14502)
	at n.value (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:8481)
	at l.y (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:664)
	at l.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:881)
	at s.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14502)
	at MessagePortMain.<anonymous> (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:6631)
	at MessagePortMain.emit (node:events:514:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
2024-05-27 00:36:19.630 [error] [ninoseki.vscode-mogami] provider FAILED
2024-05-27 00:36:19.630 [error] Error: [getWordRangeAtPosition]: ignoring custom regexp '^(?<name>)(?<rest>.+)?$' because it matches the empty string.
	at d.y (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:1838)
	at Object.getWordRangeAtPosition (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:256)
	at vc.parseDocumentPosition (c:\software\VSCode-Insiders\data\extensions\ninoseki.vscode-mogami-0.0.20\dist\extension.js:34:753)
	at vc.provideHover (c:\software\VSCode-Insiders\data\extensions\ninoseki.vscode-mogami-0.0.20\dist\extension.js:32:3314)
	at I.provideHover (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:101281)
	at c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:132072
	at Ie.s (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:129479)
	at Ie.$provideHover (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:132059)
	at E.S (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5970)
	at E.Q (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5736)
	at E.M (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:4723)
	at E.L (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:3589)
	at n.value (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:2282)
	at l.y (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:664)
	at l.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:881)
	at s.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14502)
	at n.value (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:8481)
	at l.y (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:664)
	at l.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:881)
	at s.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14502)
	at MessagePortMain.<anonymous> (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:6631)
	at MessagePortMain.emit (node:events:514:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)

**Comment by ninoseki** [comment]
I still don't understand why. Could you share pyproject.toml, please?

**Comment by yuuuxt** [comment]
```toml
[tool.poetry]
name = "a-package"
version = "0.1.0"
description = ""
authors = ["an-email"]
readme = "README.md"
packages = [{include = "a-package"}]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "0.111.0"
uvicorn = "0.29.0"
pandas = "1.5.3"
pyarrow = "16.0.0"
returns = "0.22.0"

[tool.poetry.group.dev.dependencies]
pytest = "8.2.0"
pytest-dotenv = "0.5.2"
ipykernel = "6.29.4"
pre-commit = "3.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    # "I",  # isort
    "C", # flake8-comprehensions
    "B", # flake8-bugbear
]
ignore = [
    "E501", # line too long, handled by black
    "B008", # do not perform function calls in argument defaults
    "C901", # too complex
    "F401", # imported but not used
    "B905", # zip's strict parameter
]

[tool.pytest.ini_options]
env_files = [
    ".env"
]
filterwarnings = [
    'ignore:pkg_resources is deprecated',
    'ignore:lib2to3 package is deprecated'
]
```

**Comment by ninoseki** [comment]
Hmm, it works.

<img width="413" alt="Screenshot 2024-05-27 at 2 07 08" src="https://github.com/ninoseki/vscode-mogami/assets/291028/d4993348-44d6-4d1c-915e-94f6567382b6">

**Comment by ninoseki** [comment]
I don't know but maybe restarting VS Code can solve something.

**Comment by yuuuxt** [comment]
> I don't know but maybe restarting VS Code can solve something.

of course - I just updated vscode insider version (so surely restarted).

**Comment by ninoseki** [comment]
Hmm, insider version? I overlooked your first comment and I don't test this extension in the insider version. 
I would say the insider version is out of the support.

**Comment by yuuuxt** [comment]
also I mentioned it's not working for me in the stable version. the logs are:

> 2024-05-26 22:23:20.890 [error] [ninoseki.vscode-mogami] provider FAILED
2024-05-26 22:23:20.890 [error] Error: [getWordRangeAtPosition]: ignoring custom regexp '^(?<name>)(?<rest>.+)?$' because it matches the empty string.
	at p.y (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:1838)
	at Object.getWordRangeAtPosition (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:256)
	at vc.parseDocumentPosition (c:\Users\<username>\.vscode\extensions\ninoseki.vscode-mogami-0.0.20\dist\extension.js:34:753)
	at vc.provideHover (c:\Users\<username>\.vscode\extensions\ninoseki.vscode-mogami-0.0.20\dist\extension.js:32:3314)
	at k.provideHover (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:93838)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:122706
	at Ae.s (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:120151)
	at Ae.$provideHover (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:122693)
	at c.S (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5505)
	at c.Q (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5271)
	at c.M (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:4323)
	at c.L (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:3440)
	at a.value (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:2227)
	at o.y (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:660)
	at o.fire (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:877)
	at u.fire (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14175)
	at a.value (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:8023)
	at o.y (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:660)
	at o.fire (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:877)
	at u.fire (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14175)
	at MessagePortMain.<anonymous> (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:6303)
	at MessagePortMain.emit (node:events:517:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)

and the vscode version is
```

**Comment by yuuuxt** [comment]
and just to confirm - I tested in a windows sandbox with a clean user install of the current latest sable version (1.89.1), and the issue is the same (so skipping the error message)

![image](https://github.com/ninoseki/vscode-mogami/assets/3153534/e6c8b081-ad94-46f4-a789-127aa0e9f510)

**Comment by yuuuxt** [comment]
I just tested the latest v0.0.21 and seems it hasn't started working for me. Is there anything you need for debugging?

**Comment by yuuuxt** [comment]
in v0.0.22 I see hovering labels back, but the hints haven't shown yet. same behaviour for stable and insider version (logs from insider version):

extension host (not mentioning Mogami but in insider only Mogami is installed):
> error] Canceled: Canceled
	at new A (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:50609)
	at E.U (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:6007)
	at z.<computed>.N.charCodeAt.R.CharCode.DollarSign.z.<computed> (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:3091)
	at h.g (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:199295)
	at h.executeCommand (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:198733)
	at I.registerCommand.description (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:198057)
	at h (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:199834)
	at h.g (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:198826)
	at h.executeCommand (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:198733)
	at Object.executeCommand (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:163:22742)
	at set hasGitHubRepositories (c:\software\VSCode-Insiders\resources\app\extensions\github\dist\extension.js:2:322969)
	at c:\software\VSCode-Insiders\resources\app\extensions\github\dist\extension.js:2:323928
	at n.value (c:\software\VSCode-Insiders\resources\app\extensions\git\dist\main.js:2:1050764)
	at l.y (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:664)
	at l.z (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:734)
	at l.fire (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:950)
	at Object.p [as dispose] (c:\software\VSCode-Insiders\resources\app\extensions\git\dist\main.js:2:964275)
	at c:\software\VSCode-Insiders\resources\app\extensions\git\dist\main.js:2:970313
	at Array.forEach (<anonymous>)
	at f.dispose (c:\software\VSCode-Insiders\resources\app\extensions\git\dist\main.js:2:970299)
	at a.<anonymous> (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:4032)
	at a.dispose (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:4129)
	at a.<anonymous> (c:\software\VSCode-Insiders\resources\app\extensions\git\dist\main.js:2:947448)
	at a.dispose (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:4129)
	at f (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:30:744)
	at u.eb (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:159:9991)
	at c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:159:7867
	at Array.map (<anonymous>)
	at u.$ (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:159:7854)
	at u.terminate (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:159:8127)
	at f.terminate (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:163:1513)
	at t (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:10459)
	at MessagePortMain.<anonymous> (c:\software\VSCode-Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:6675)
	at MessagePortMain.emit (node:events:514:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285) setContext undefined

Mogami log: only multiple `[info] Poetry detected: 9 dependencies found` rows, no error there.

**Comment by ninoseki** [comment]
Same as https://github.com/ninoseki/vscode-mogami/issues/38#issuecomment-2134977801

**Comment by ninoseki** [comment]
I will close this PR since there is no response over a week.

**Comment by yuuuxt** [comment]
Sorry but what response did you expect? The logs were provided and I haven't found any changes in the versions thereafter.

**Comment by Nathan-Heller** [comment]
I havent been able to figure out why, but the hints havent been working for me for forever either. 

I tried wiping my User-level `settings.json` to see if there was some setting causing a conflict, but no dice, the codelens hints still never appear.
