### ISSUE TITLE
Code lens crash when a dependency includes another

### ISSUE THREAD

**Issue by jorenham** [ninoseki/vscode-mogami#94]
### Describe the bug

PEP 735 defines a way to include a groups in another one: https://peps.python.org/pep-0735/#dependency-group-include. 

But when I attempt this, codelens raises an error, and stops working alltogether. This is what I see in the `Extension Host` logs:

```
2024-11-07 00:47:31.421 [error] [ninoseki.vscode-mogami] provider FAILED
2024-11-07 00:47:31.423 [error] Error: Unsupported project format
	at Mm (/home/joren/.vscode/extensions/ninoseki.vscode-mogami-0.0.36/dist/extension.js:74:1549)
	at Vg.provideHover (/home/joren/.vscode/extensions/ninoseki.vscode-mogami-0.0.36/dist/extension.js:81:41245)
	at MC.provideHover (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:128499)
	at file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:156649
	at qt.s (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:154117)
	at qt.$provideHover (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:156637)
	at py.S (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113311)
	at py.Q (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113091)
	at py.M (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112142)
	at py.L (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111285)
	at mh.value (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110082)
	at D.B (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
	at D.fire (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
	at Vn.fire (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
	at mh.value (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:13279)
	at D.B (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
	at D.fire (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
	at Vn.fire (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
	at MessagePortMain.<anonymous> (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11571)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain.emit (node:domain:488:12)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
```

Without these includes, codelens is working like a charm 👌🏻 

### Reproduction

```toml
[dependency-groups]
awesome = [
    "scipy-stubs",
]
dev = [
    {include-group = "awesome"},
]
```

FWIW; `uv` is able to parse this just fine, so I don't think I'm doing anything wrong

**Comment by ninoseki** [comment]
This project uses [@iarna/toml](https://github.com/iarna/iarna-toml) and it failes to parse mixed inline-table/list.

```ts
import toml from '@iarna/toml'

const parsed = toml.parse(
  `  
[dependency-groups]
test = ["pytest", "coverage"]
docs = ["sphinx", "sphinx-rtd-theme"]
typing = ["mypy", "types-requests"]
typing-test = [{include-group = "typing"}, {include-group = "test"}, "useful-types"]
`
)
console.log(parsed)
```

```
/.../node_modules/@iarna/toml/lib/toml-parser.js:1305
          throw this.error(new TomlError(`Inline lists must be a single type, not a mix of ${listType} and ${valueType}`))
                           ^

TomlError: Inline lists must be a single type, not a mix of inline-table and string at row 6, col 84, pos 211:
5: typing = ["mypy", "types-requests"]
6> typing-test = [{include-group = "typing"}, {include-group = "test"}, "useful-types"]
```

Hmm.

**Comment by jorenham** [comment]
I've seen people switch to https://github.com/squirrelchat/smol-toml recently, because other libraries weren't able to parse emoji's 🤷🏻

**Comment by ninoseki** [comment]
Thanks for the heads up and giving a hint. I think the issue is fixed in the latest version.
